---
engines:
  eslint:
    enabled: false
  jacksonlinter:
    enabled: false
exclude_paths:
  - "**/bin/**"
  - "**/obj/**"
  - "**/packages/**"
  - "**/Resources/**"
  - "**/*.Designer.cs"
  - "**/*.resx"
  - "**/*.ico"
  - "**/*.png"
  - "**/*.pfx"