---
engines:
  eslint:
    enabled: false
  jacksonlinter:
    enabled: false
  remark-lint:
    enabled: false
exclude_paths:
  - '**/bin/**'
  - '**/obj/**'
  - '**/packages/**'
  - '**/Resources/**'
  - '**/Properties/**'
  - '**/*.resx'
  - '**/*.resources'
  - '**/*.json'
  - '**/*.config'
  - '**/*.sln'
  - '**/*.csproj'